Repository vmware-tanzu/pinniped, pull requests merged in 2020-10, with the labels that each got.

#138 Do not append "-dirty" to the version number when the git repo is dirty
  hack/lib/version.sh
Labels: cla-not-required

#141 Minor docs updates
  deploy-local-user-authenticator/README.md
Labels: cla-not-required

#142 Remove curly braces from doc commands
  doc/demo.md
Labels: cla-not-required

#140 Rename the CoC and contributor guide to the names GitHub recognizes.
  .github/pull_request_template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  doc/scope.md
Labels: cla-not-required

#146 Add Tilt-based local dev workflow.
  .gitignore
  .pre-commit-config.yaml
  CONTRIBUTING.md
  cmd/pinniped-server/main.go
  deploy/deployment.yaml
  deploy/values.yaml
  hack/lib/tilt/Tiltfile
  hack/lib/tilt/local-user-authenticator.Dockerfile
  hack/lib/tilt/pinniped.Dockerfile
  hack/lib/tilt/tilt_modules/docker_build_sub/Tiltfile
  hack/lib/tilt/tilt_modules/extensions.json
  hack/lib/tilt/tilt_modules/restart_process/Tiltfile
  hack/prepare-for-integration-tests.sh
  hack/tilt-down.sh
  hack/tilt-up.sh
Labels: cla-not-required

#147 Implement initial steps of OIDC CLI client.
  cmd/pinniped/cmd/alpha.go
  cmd/pinniped/cmd/cobra_util.go
  cmd/pinniped/cmd/cobra_util_test.go
  cmd/pinniped/cmd/get_kubeconfig.go
  cmd/pinniped/cmd/login.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  go.mod
  go.sum
  internal/oidc/pkce/pkce.go
  internal/oidc/pkce/pkce_test.go
  internal/oidc/state/state.go
  internal/oidc/state/state_test.go
Labels: cla-not-required

#151 Add demo screencast and do some cleanup in demo.md
  doc/demo.md
Labels: cla-not-required, hacktoberfest-accepted

#149 Finish initial OIDC CLI client implementation.
  CONTRIBUTING.md
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  go.mod
  go.sum
  hack/lib/kind-config/multi-node.yaml
  hack/lib/kind-config/single-node.yaml
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  internal/httputil/httperr/httperr.go
  internal/httputil/httperr/httperr_test.go
  internal/httputil/securityheader/securityheader.go
  internal/httputil/securityheader/securityheader_test.go
  internal/mocks/mockkeyset/generate.go
  internal/mocks/mockkeyset/mockkeyset.go
  internal/oidc/state/state.go
  internal/oidcclient/login/login.go
  internal/oidcclient/login/login_test.go
  internal/oidcclient/nonce/nonce.go
  internal/oidcclient/nonce/nonce_test.go
  internal/oidcclient/pkce/pkce.go
  internal/oidcclient/pkce/pkce_test.go
  internal/oidcclient/state/state.go
  internal/oidcclient/state/state_test.go
  test/deploy/dex/dex.yaml
  test/deploy/dex/values.yaml
  test/integration/cli_test.go
  test/library/env.go
Labels: cla-not-required

#157 Pinniped federation server generates and persists a JWT signing key
  apis/config/v1alpha1/types_oidcproviderconfig.go.tmpl
  cmd/pinniped-supervisor/main.go
  deploy/supervisor/config.pinniped.dev_oidcproviderconfigs.yaml
  deploy/supervisor/rbac.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.17/apis/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/client/openapi/zz_generated.openapi.go
  generated/1.17/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.18/apis/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/client/openapi/zz_generated.openapi.go
  generated/1.18/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.19/apis/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/client/openapi/zz_generated.openapi.go
  generated/1.19/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  internal/controller/supervisorconfig/jwks.go
  internal/controller/supervisorconfig/jwks_test.go
  internal/controller/supervisorconfig/testdata/good-ec-key.pem
  internal/controller/supervisorconfig/testdata/good-jwk.json
  internal/controller/supervisorconfig/testdata/good-jwks.json
  internal/controller/supervisorconfig/testdata/invalid-key-jwk.json
  internal/controller/supervisorconfig/testdata/invalid-key-jwks.json
  internal/controller/supervisorconfig/testdata/missing-active-jwks.json
  internal/controller/supervisorconfig/testdata/not-json.txt
  internal/controller/supervisorconfig/testdata/private-jwks.json
  internal/controller/supervisorconfig/testdata/public-jwk.json
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_keys_test.go
  test/library/client.go
Labels: cla-not-required

#158 Custom labels can to be applied to all k8s resources created by Pinniped
  Dockerfile
  cmd/local-user-authenticator/main.go
  cmd/pinniped-supervisor/main.go
  deploy/concierge/deployment.yaml
  deploy/concierge/helpers.lib.yaml
  deploy/concierge/rbac.yaml
  deploy/concierge/values.yaml
  deploy/concierge/z0_crd_overlay.yaml
  deploy/local-user-authenticator/values.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/helpers.lib.yaml
  deploy/supervisor/rbac.yaml
  deploy/supervisor/service.yaml
  deploy/supervisor/values.yaml
  deploy/supervisor/z0_crd_overlay.yaml
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  internal/concierge/server/server.go
  internal/config/concierge/config.go
  internal/config/concierge/config_test.go
  internal/config/concierge/types.go
  internal/config/supervisor/config.go
  internal/config/supervisor/config_test.go
  internal/config/supervisor/types.go
  internal/controller/apicerts/certs_manager.go
  internal/controller/apicerts/certs_manager_test.go
  internal/controller/issuerconfig/create_or_update_credential_issuer_config.go
  internal/controller/issuerconfig/create_or_update_credential_issuer_config_test.go
  internal/controller/issuerconfig/kube_config_info_publisher.go
  internal/controller/issuerconfig/kube_config_info_publisher_test.go
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/creater_test.go
  internal/controller/kubecertagent/execer.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/controller/supervisorconfig/jwks.go
  internal/controller/supervisorconfig/jwks_test.go
  internal/controllermanager/prepare_controllers.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_credentialissuerconfig_test.go
  test/integration/concierge_kubecertagent_test.go
  test/integration/supervisor_keys_test.go
  test/library/env.go
Labels: cla-not-required

#163 Implement per-issuer OIDC JWKS endpoint
  cmd/pinniped-supervisor/main.go
  internal/controller/identityprovider/webhookcachecleaner/webhookcachecleaner.go
  internal/controller/identityprovider/webhookcachefiller/webhookcachefiller.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/jwks_observer_test.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/jwks_writer_test.go
  internal/controller/supervisorconfig/oidcproviderconfig_watcher.go
  internal/controller/supervisorconfig/testdata/public-jwk2.json
  internal/controller/utils.go
  internal/oidc/discovery/discovery_handler.go
  internal/oidc/discovery/discovery_handler_test.go
  internal/oidc/jwks/dynamic_jwks_provider.go
  internal/oidc/jwks/jwks_handler.go
  internal/oidc/jwks/jwks_handler_test.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required

#164 Virtual hosts integration test
  hack/prepare-for-integration-tests.sh
  test/integration/supervisor_discovery_test.go
  test/library/env.go
Labels: cla-not-required

#165 Add basic file-based session cache for CLI OIDC client.
  cmd/pinniped/cmd/cobra_util.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  go.mod
  internal/oidcclient/filesession/cachefile.go
  internal/oidcclient/filesession/cachefile_test.go
  internal/oidcclient/filesession/filesession.go
  internal/oidcclient/filesession/filesession_test.go
  internal/oidcclient/filesession/testdata/invalid.yaml
  internal/oidcclient/filesession/testdata/valid.yaml
  internal/oidcclient/filesession/testdata/wrong-version.yaml
  internal/oidcclient/login.go
  internal/oidcclient/login_test.go
  internal/oidcclient/types.go
  test/integration/cli_test.go
Labels: cla-not-required, enhancement, go

#166 Add some verbose logging to TestCLILoginOIDC.
  test/integration/cli_test.go
  test/library/iotest.go
Labels: cla-not-required

#167 Fix a timeout in TestCLILoginOIDC that was accidentally shortened.
  test/integration/cli_test.go
Labels: cla-not-required

#168 Add support for refresh token flow in OIDC CLI client.
  internal/oidcclient/login.go
  internal/oidcclient/login_test.go
  test/integration/cli_test.go
Labels: cla-not-required

#169 Promote the `pinniped login` command out of alpha.
  cmd/pinniped/cmd/login.go
  test/integration/cli_test.go
Labels: cla-not-required, enhancement

#171 Rename logo file
  README.md
  doc/img/pinniped_logo.svg
Labels: cla-not-required

#170 Add HTTPS endpoints for OIDC providers, and terminate TLS with the configured certificates
  apis/config/v1alpha1/types_oidcproviderconfig.go.tmpl
  cmd/local-user-authenticator/main.go
  cmd/local-user-authenticator/main_test.go
  cmd/pinniped-supervisor/main.go
  deploy/supervisor/README.md
  deploy/supervisor/config.pinniped.dev_oidcproviderconfigs.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/service.yaml
  deploy/supervisor/values.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.17/client/openapi/zz_generated.openapi.go
  generated/1.17/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.18/client/openapi/zz_generated.openapi.go
  generated/1.18/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/config/v1alpha1/types_oidcproviderconfig.go
  generated/1.19/client/openapi/zz_generated.openapi.go
  generated/1.19/crds/config.pinniped.dev_oidcproviderconfigs.yaml
  hack/lib/kind-config/single-node.yaml
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  internal/certauthority/certauthority.go
  internal/certauthority/certauthority_test.go
  internal/config/supervisor/config.go
  internal/config/supervisor/config_test.go
  internal/config/supervisor/types.go
  internal/controller/apicerts/certs_manager.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/oidcproviderconfig_watcher.go
  internal/controller/supervisorconfig/oidcproviderconfig_watcher_test.go
  internal/controller/supervisorconfig/testdata/test.crt
  internal/controller/supervisorconfig/testdata/test.key
  internal/controller/supervisorconfig/testdata/test2.crt
  internal/controller/supervisorconfig/testdata/test2.key
  internal/controller/supervisorconfig/testdata/test3.crt
  internal/controller/supervisorconfig/testdata/test3.key
  internal/controller/supervisorconfig/tls_cert_observer.go
  internal/controller/supervisorconfig/tls_cert_observer_test.go
  internal/oidc/provider/dynamic_tls_cert_provider.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  internal/oidc/provider/oidcprovider.go
  internal/oidc/provider/oidcprovider_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_keys_test.go
  test/library/client.go
  test/library/env.go
Labels: cla-not-required

#173 Do codegen across all version in parallel.
  hack/update.sh
Labels: cla-not-required
