Repository vmware-tanzu/pinniped, pull requests merged in 2020-12, with the labels that each got.

#250 Fix a test regression with IPv6 localhost interfaces.
  test/integration/supervisor_discovery_test.go
  test/library/iplookup.go
  test/library/iplookup_go1.14.go
Labels: bug, cla-not-required

#229 Implement supervisor OIDC upstream callback endpoint used during authorize flow
  cmd/pinniped-supervisor/main.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  go.mod
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  internal/certauthority/certauthority.go
  internal/certauthority/certauthority_test.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  internal/crud/crud.go
  internal/crud/crud_test.go
  internal/fosite/authorizationcode/authorizationcode_test.go
  internal/fositestorage/authorizationcode/authorizationcode.go
  internal/fositestorage/authorizationcode/authorizationcode_test.go
  internal/fositestorage/fositestorage.go
  internal/fositestorage/openidconnect/openidconnect.go
  internal/fositestorage/openidconnect/openidconnect_test.go
  internal/fositestorage/pkce/pkce.go
  internal/fositestorage/pkce/pkce_test.go
  internal/mocks/mockupstreamoidcidentityprovider/generate.go
  internal/mocks/mockupstreamoidcidentityprovider/mockupstreamoidcidentityprovider.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/kube_storage.go
  internal/oidc/nullstorage.go
  internal/oidc/oidc.go
  internal/oidc/oidctestutil/oidc.go
  internal/oidc/provider/dynamic_upstream_idp_provider.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  internal/testutil/assertions.go
  internal/upstreamoidc/upstreamoidc.go
  internal/upstreamoidc/upstreamoidc_test.go
  pkg/oidcclient/filesession/cachefile.go
  pkg/oidcclient/filesession/cachefile_test.go
  pkg/oidcclient/filesession/filesession.go
  pkg/oidcclient/filesession/filesession_test.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  pkg/oidcclient/oidctypes/oidctypes.go
  test/deploy/dex/dex.yaml
  test/deploy/dex/proxy.yaml
  test/deploy/dex/values.yaml
  test/integration/cli_test.go
  test/integration/storage_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_keys_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_upstream_test.go
  test/library/browsertest/browsertest.go
  test/library/client.go
  test/library/dumplogs.go
  test/library/iotest.go
Labels: cla-not-required

#252 Switch CSRF cookie from `Same-Site=Strict` to `Same-Site=Lax`.
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
Labels: bug, cla-not-required

#257 Prefactor before adding CLI "request audience" functionality.
  internal/mocks/mockupstreamoidcidentityprovider/mockupstreamoidcidentityprovider.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/oidctestutil/oidc.go
  internal/oidc/provider/dynamic_upstream_idp_provider.go
  internal/oidc/provider/manager/manager_test.go
  internal/upstreamoidc/upstreamoidc.go
  internal/upstreamoidc/upstreamoidc_test.go
  pkg/oidcclient/filesession/cachefile_test.go
  pkg/oidcclient/filesession/testdata/valid.yaml
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  pkg/oidcclient/oidctypes/oidctypes.go
Labels: cla-not-required

#255 Remove "email" and "profile" from default scopes requested by CLI.
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  test/integration/cli_test.go
Labels: cla-not-required, enhancement

#261 Disable the goerr113 linter.
  .golangci.yaml
  internal/controllerlib/option.go
  internal/controllerlib/test/integration/examplecontroller/controller/creating.go
  internal/controllerlib/test/integration/examplecontroller/controller/updating.go
Labels: cla-not-required

#259 Add a `--request-audience` flag to the `pinniped login oidc` CLI command
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
Labels: cla-not-required, enhancement

#265 Use constants for scope values
  cmd/pinniped/cmd/login_oidc.go
  pkg/oidcclient/login.go
Labels: cla-not-required

#266 Fix `JWTAuthenticator` CA bundle
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  test/library/client.go
Labels: cla-not-required

#262 Support for the refresh grant in the supervisor's token endpoint
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/kube_storage.go
  internal/oidc/nullstorage_test.go
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
Labels: cla-not-required

#267 Implement RFC8693 token exchange handler in the supervisor
  internal/crud/crud.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/nullstorage_test.go
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
  internal/oidc/token_exchange.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#268 Secret generation prefactor
  internal/oidc/auth/auth_handler.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
Labels: cla-not-required

#270 Add a default --client-id in `pinniped login oidc` command.
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
Labels: cla-not-required, enhancement

#271 Fix bug in handling response content-type in oidcclient.
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
Labels: bug, cla-not-required

#272 Tweak default CLI `--scopes` parameter to match supervisor use case.
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
Labels: cla-not-required, enhancement

#275 Fosite storage garbage collection prefactor
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/token/token_handler_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#274 WIP: garbage collect the fosite secrets to limit amount of storage used
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/token/token_handler_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#278 Garbage collect the fosite secrets to limit amount of storage used
  cmd/pinniped-supervisor/main.go
  internal/controller/supervisorstorage/garbage_collector.go
  internal/controller/supervisorstorage/garbage_collector_test.go
  internal/crud/crud.go
  internal/crud/crud_test.go
  internal/fositestorage/accesstoken/accesstoken.go
  internal/fositestorage/accesstoken/accesstoken_test.go
  internal/fositestorage/authorizationcode/authorizationcode.go
  internal/fositestorage/authorizationcode/authorizationcode_test.go
  internal/fositestorage/openidconnect/openidconnect.go
  internal/fositestorage/openidconnect/openidconnect_test.go
  internal/fositestorage/pkce/pkce.go
  internal/fositestorage/pkce/pkce_test.go
  internal/fositestorage/refreshtoken/refreshtoken.go
  internal/fositestorage/refreshtoken/refreshtoken_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/kube_storage.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/token/token_handler_test.go
  test/integration/supervisor_storage_garbage_collection_test.go
  test/integration/supervisor_storage_test.go
Labels: cla-not-required

#279 Update more fosite settings
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/dynamic_open_id_connect_ecdsa_strategy_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager_test.go
  internal/oidc/token/token_handler_test.go
Labels: cla-not-required

#282 Add Cache-Control, Pragma, Expires, and X-DNS-Prefetch-Control headers
  internal/httputil/securityheader/securityheader.go
  internal/httputil/securityheader/securityheader_test.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/testutil/assertions.go
Labels: cla-not-required

#284 SameIssuerHostMustUseSameSecret is a valid OIDCProvider status, and help some test flakes
  apis/supervisor/config/v1alpha1/types_oidcprovider.go.tmpl
  deploy/supervisor/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.17/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.17/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.18/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.18/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.19/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.19/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  test/integration/supervisor_login_test.go
  test/library/client.go
Labels: cla-not-required

#276 Enhance CLI to integrate supervisor and concierge capabilities.
  cmd/pinniped/cmd/deprecated.go
  cmd/pinniped/cmd/exchange_credential.go
  cmd/pinniped/cmd/exchange_credential_test.go
  cmd/pinniped/cmd/get.go
  cmd/pinniped/cmd/get_kubeconfig.go
  cmd/pinniped/cmd/get_kubeconfig_test.go
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static.go
  cmd/pinniped/cmd/login_static_test.go
  go.mod
  pkg/conciergeclient/conciergeclient.go
  pkg/conciergeclient/conciergeclient_test.go
  test/integration/cli_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/e2e_test.go
  test/library/cli.go
  test/library/client.go
  test/library/env.go
Labels: cla-not-required, enhancement

#285 Log when unexpected Upstream OIDC Providers found
  internal/oidc/auth/auth_handler.go
Labels: cla-not-required

#289 Fix documentation comment for the UpstreamOIDCProvider's spec.client.secretName type.
  apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go.tmpl
  deploy/supervisor/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.17/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.18/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.19/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
Labels: bug, cla-not-required

#288 Fix a regression in securityheaders package and add tests.
  internal/httputil/securityheader/securityheader.go
  internal/httputil/securityheader/securityheader_test.go
  internal/testutil/assertions.go
  test/integration/supervisor_login_test.go
Labels: bug, cla-not-required

#291 Tweak timeouts in oidcclient package.
  pkg/oidcclient/login.go
Labels: cla-not-required, enhancement

#292 Upgrade golang (1.15.5 -> 1.15.6)
  Dockerfile
Labels: cla-not-required

#286 Upgrade base images to Debian 10.7-slim.
  Dockerfile
  hack/lib/tilt/Tiltfile
  hack/lib/tilt/concierge.Dockerfile
  hack/lib/tilt/local-user-authenticator.Dockerfile
  hack/lib/tilt/supervisor.Dockerfile
  test/deploy/dex/proxy.yaml
Labels: cla-not-required

#290 Rename the "pinniped.sts.unrestricted" scope to "pinniped:request-audience".
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/nullstorage_test.go
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
  internal/oidc/token_exchange.go
  pkg/oidcclient/login.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#273 Generate secrets for Pinniped Supervisor
  apis/supervisor/config/v1alpha1/types_oidcprovider.go.tmpl
  cmd/pinniped-supervisor/main.go
  deploy/supervisor/config.supervisor.pinniped.dev_oidcproviders.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/rbac.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.17/apis/supervisor/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.18/apis/supervisor/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.19/apis/supervisor/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  internal/controller/supervisorconfig/generator/generator.go
  internal/controller/supervisorconfig/generator/oidc_provider_secrets.go
  internal/controller/supervisorconfig/generator/oidc_provider_secrets_test.go
  internal/controller/supervisorconfig/generator/secret_helper.go
  internal/controller/supervisorconfig/generator/secret_helper_test.go
  internal/controller/supervisorconfig/generator/supervisor_secrets.go
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/jwks_observer_test.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/jwks_writer_test.go
  internal/downward/downward.go
  internal/downward/downward_test.go
  internal/downward/testdata/valid/name
  internal/downward/testdata/validwithoutname/labels
  internal/downward/testdata/validwithoutname/namespace
  internal/mocks/mocksecrethelper/generate.go
  internal/mocks/mocksecrethelper/mocksecrethelper.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/dynamic_oauth2_hmac_strategy.go
  internal/oidc/dynamiccodec/codec.go
  internal/oidc/dynamiccodec/codec_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  internal/oidc/token/token_handler_test.go
  internal/secret/cache.go
  internal/secret/cache_test.go
  test/integration/e2e_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_keys_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_secrets_test.go
  test/library/client.go
Labels: cla-not-required

#283 Adjust subject and username claims
  apis/concierge/authentication/v1alpha1/types_jwt.go.tmpl
  deploy/concierge/authentication.concierge.pinniped.dev_jwtauthenticators.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/concierge/authentication/v1alpha1/types_jwt.go
  generated/1.17/apis/concierge/authentication/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/authentication.concierge.pinniped.dev_jwtauthenticators.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/concierge/authentication/v1alpha1/types_jwt.go
  generated/1.18/apis/concierge/authentication/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/authentication.concierge.pinniped.dev_jwtauthenticators.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/concierge/authentication/v1alpha1/types_jwt.go
  generated/1.19/apis/concierge/authentication/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/authentication.concierge.pinniped.dev_jwtauthenticators.yaml
  internal/controller/authenticator/jwtcachefiller/jwtcachefiller.go
  internal/controller/authenticator/jwtcachefiller/jwtcachefiller_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/supervisor_login_test.go
  test/library/client.go
Labels: cla-not-required

#295 Only set single secret status field in FederationDomainSecretsController
  cmd/pinniped-supervisor/main.go
  internal/controller/supervisorconfig/generator/oidc_provider_secrets.go
  internal/controller/supervisorconfig/generator/oidc_provider_secrets_test.go
Labels: cla-not-required

#143 Enable cache mutation detector in unit tests
  hack/module.sh
  internal/controller/controller_test.go
Labels: cla-not-required, hacktoberfest-accepted

#281 Upgrade the Dex we use for local testing to v2.27.0.
  test/deploy/dex/dex.yaml
Labels: cla-not-required

#298 Rename all "op" and "opc" usages
  cmd/pinniped-supervisor/main.go
  internal/controller/supervisorconfig/federation_domain_watcher.go
  internal/controller/supervisorconfig/federation_domain_watcher_test.go
  internal/controller/supervisorconfig/generator/federation_domain_secrets.go
  internal/controller/supervisorconfig/generator/federation_domain_secrets_test.go
  internal/controller/supervisorconfig/generator/generator.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/jwks_writer_test.go
  internal/oidc/provider/federation_domain_issuer.go
  internal/oidc/provider/federation_domain_issuer_test.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  test/integration/supervisor_discovery_test.go
  test/library/client.go
Labels: cla-not-required

#300 Even more "op" and "opc" local variable renames
  cmd/pinniped-supervisor/main.go
  internal/controller/supervisorconfig/generator/generator.go
  internal/controller/supervisorconfig/generator/secret_helper.go
  internal/controller/supervisorconfig/generator/secret_helper_test.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  test/integration/supervisor_secrets_test.go
Labels: cla-not-required

#299 Update dependencies before v0.3.0 release.
  Dockerfile
  cmd/pinniped/cmd/get.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static_test.go
  cmd/pinniped/cmd/version_test.go
  generated/1.19/apis/go.mod
  generated/1.19/apis/go.sum
  generated/1.19/client/go.mod
  generated/1.19/client/go.sum
  go.mod
  go.sum
  hack/lib/kube-versions.txt
  hack/lib/update-codegen.sh
  hack/module.sh
  internal/fositestorage/accesstoken/accesstoken.go
  internal/fositestorage/authorizationcode/authorizationcode.go
  internal/fositestorage/authorizationcode/authorizationcode_test.go
  internal/fositestorage/openidconnect/openidconnect.go
  internal/fositestorage/pkce/pkce.go
  internal/fositestorage/refreshtoken/refreshtoken.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/dynamic_open_id_connect_ecdsa_strategy.go
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
  internal/oidc/token_exchange.go
  tools/tools.go
Labels: cla-not-required

#302 Move our main image references to the VMware Harbor registry.
  deploy/concierge/values.yaml
  deploy/local-user-authenticator/values.yaml
  deploy/supervisor/values.yaml
  hack/prepare-for-integration-tests.sh
  test/deploy/dex/proxy.yaml
Labels: cla-not-required

#301 Put a Type on all of the Secrets that we create in the supervisor
  internal/controller/supervisorconfig/generator/federation_domain_secrets.go
  internal/controller/supervisorconfig/generator/generator.go
  internal/controller/supervisorconfig/generator/secret_helper.go
  internal/controller/supervisorconfig/generator/secret_helper_test.go
  internal/controller/supervisorconfig/generator/supervisor_secrets.go
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/jwks_writer_test.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  test/integration/supervisor_secrets_test.go
Labels: cla-not-required

#306 Fix a website typo and add an "Installing Pinniped" docs page.
  site/config.yaml
  site/content/docs/install.md
  site/content/docs/scope.md
Labels: cla-not-required, website

#297 Update docs for Supervisor
  CONTRIBUTING.md
  README.md
  site/content/docs/ADOPTERS.md
  site/content/docs/CODE_OF_CONDUCT.md
  site/content/docs/CONTRIBUTING.md
  site/content/docs/LICENSE
  site/content/docs/MAINTAINERS.md
  site/content/docs/SECURITY.md
  site/content/docs/architecture.md
  site/content/docs/concierge-and-supervisor-demo.md
  site/content/docs/concierge-only-demo.md
  site/content/docs/demo.md
  site/content/docs/img/README.md
  site/content/docs/img/pinniped-concierge-sequence.svg
  site/content/docs/img/pinniped-concierge-sequence.txt
  site/content/docs/img/pinniped-concierge-supervisor-sequence.svg
  site/content/docs/img/pinniped-concierge-supervisor-sequence.txt
  site/content/docs/img/pinniped_architecture_concierge_supervisor.svg
  site/content/docs/img/pinniped_architecture_concierge_webhook.svg
Labels: cla-not-required, website

#305 Sync Secret-watching controller less often by adjusting their filters to be more specific
  cmd/pinniped-supervisor/main.go
  internal/controller/supervisorconfig/generator/federation_domain_secrets.go
  internal/controller/supervisorconfig/generator/federation_domain_secrets_test.go
  internal/controller/supervisorconfig/generator/secret_helper.go
  internal/controller/supervisorconfig/generator/secret_helper_test.go
  internal/controller/supervisorconfig/generator/supervisor_secrets.go
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/jwks_observer_test.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/jwks_writer_test.go
  internal/controller/supervisorconfig/tls_cert_observer.go
  internal/controller/supervisorconfig/tls_cert_observer_test.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  internal/controller/supervisorstorage/garbage_collector.go
  internal/controller/supervisorstorage/garbage_collector_test.go
  internal/controller/utils.go
  internal/mocks/mocksecrethelper/mocksecrethelper.go
  test/integration/e2e_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_storage_garbage_collection_test.go
  test/library/client.go
Labels: cla-not-required
