Repository vmware-tanzu/pinniped, pull requests merged in 2020-11, with the labels that each got.

#176 Handle custom labels better in the agent pod controllers
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/annotater_test.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/creater_test.go
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/deleter_test.go
  internal/controller/kubecertagent/kubecertagent.go
Labels: cla-not-required

#178 test/integration: protect from NPE and follow doc conventions
  test/integration/concierge_credentialrequest_test.go
  test/library/access.go
Labels: cla-not-required

#181 Give the concierge access to use any PodSecurityPolicy.
  deploy/concierge/rbac.yaml
Labels: cla-not-required

#183 Run as non-root
  Dockerfile
  cmd/local-user-authenticator/main.go
  cmd/pinniped-supervisor/main.go
  deploy/concierge/deployment.yaml
  deploy/local-user-authenticator/deployment.yaml
  deploy/supervisor/README.md
  deploy/supervisor/deployment.yaml
  deploy/supervisor/service.yaml
  deploy/supervisor/values.yaml
  hack/lib/tilt/concierge.Dockerfile
  hack/lib/tilt/local-user-authenticator.Dockerfile
  hack/lib/tilt/supervisor.Dockerfile
  internal/concierge/server/server.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/deleter_test.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required

#180 Add CPU/memory limits to our deployments
  deploy/concierge/deployment.yaml
  deploy/supervisor/deployment.yaml
Labels: cla-not-required

#184 Upgrade golang patch release to 1.15.3 and debian 10.5-slim -> 10.6-slim
  Dockerfile
  hack/lib/tilt/Tiltfile
  hack/lib/tilt/concierge.Dockerfile
  hack/lib/tilt/local-user-authenticator.Dockerfile
  hack/lib/tilt/supervisor.Dockerfile
Labels: cla-not-required

#154 Rename static yaml files in release process
  deploy/concierge/README.md
  deploy/supervisor/README.md
  doc/demo.md
Labels: cla-not-required, hacktoberfest-accepted

#186 gopkg.in/square/go-jose.v2: v2.2.2 -> v2.5.1
  go.mod
  go.sum
Labels: cla-not-required

#139 Use parent func to indicate when the controller queue is a singleton
  internal/controller/authenticator/webhookcachecleaner/webhookcachecleaner.go
  internal/controller/authenticator/webhookcachefiller/webhookcachefiller.go
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/execer.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/oidcproviderconfig_watcher.go
  internal/controller/supervisorconfig/tls_cert_observer.go
  internal/controller/utils.go
Labels: cla-not-required, hacktoberfest-accepted

#190 Add log level support
  cmd/local-user-authenticator/main.go
  cmd/pinniped-supervisor/main.go
  cmd/pinniped/cmd/exchange_credential.go
  cmd/pinniped/cmd/exchange_credential_test.go
  cmd/pinniped/cmd/get_kubeconfig.go
  cmd/pinniped/cmd/get_kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/version_test.go
  internal/concierge/apiserver/apiserver.go
  internal/concierge/server/server.go
  internal/concierge/server/server_test.go
  internal/config/concierge/config.go
  internal/config/concierge/types.go
  internal/config/supervisor/config.go
  internal/config/supervisor/types.go
  internal/controller/issuerconfig/kube_config_info_publisher.go
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/supervisorconfig/jwks_observer.go
  internal/controller/supervisorconfig/jwks_writer.go
  internal/controller/supervisorconfig/oidcproviderconfig_watcher.go
  internal/controller/supervisorconfig/tls_cert_observer.go
  internal/controllerlib/controller.go
  internal/controllerlib/manager.go
  internal/oidc/provider/manager/manager.go
  internal/plog/doc.go
  internal/plog/klog.go
  internal/plog/level.go
  internal/plog/level_test.go
  internal/plog/plog.go
Labels: cla-not-required

#193 Add Netlify configs for extra redirect domains.
  site/redirects/get.pinniped.dev/netlify.toml
  site/redirects/go.pinniped.dev/index.html
  site/redirects/go.pinniped.dev/netlify.toml
Labels: cla-not-required, documentation

#194 Minor website fixes and adding netlify configs
  site/config.yaml
  site/netlify.toml
Labels: cla-not-required

#195 Fix some links on the community page.
  site/config.yaml
  site/content/community/_index.html
  site/redirects/go.pinniped.dev/netlify.toml
Labels: cla-not-required, website

#196 Add YTT template value for log level
  cmd/local-user-authenticator/main.go
  deploy/concierge/deployment.yaml
  deploy/concierge/helpers.lib.yaml
  deploy/concierge/values.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/helpers.lib.yaml
  deploy/supervisor/values.yaml
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
Labels: cla-not-required

#197 Add first blog post
  site/content/posts/a-seal-of-approval.md
  site/content/posts/blog-article-1.md
Labels: cla-not-required

#185 WIP: Add Supervisor OIDC authorization endpoint
  cmd/pinniped-supervisor/main.go
  go.mod
  go.sum
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/csrftoken/csrftoken.go
  internal/oidc/nullstorage.go
  internal/oidc/nullstorage_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  internal/plog/doc.go
  internal/plog/plog.go
Labels: cla-not-required

#198 Prevent multiple pinnipeds from thrashing on the API service
  internal/controller/apicerts/apiservice_updater.go
  internal/controller/apicerts/apiservice_updater_test.go
  internal/controller/apicerts/update_api_service.go
  internal/controller/apicerts/update_api_service_test.go
Labels: cla-not-required

#200 Website fixes for broken links, formatting, and more
  site/config.yaml
  site/content/docs/_index.md
  site/content/docs/architecture.md
  site/content/docs/demo.md
  site/content/docs/img/README.md
  site/content/docs/scope.md
  site/themes/pinniped/layouts/partials/use-cases.html
Labels: cla-not-required

#204 Remove CRD count check, since we can now use wildcards.
  hack/update.sh
Labels: cla-not-required

#205 Put all of our APIs into a "pinniped" category, and never use "all".
  apis/concierge/authentication/v1alpha1/types_webhook.go.tmpl
  apis/concierge/config/v1alpha1/types_credentialissuer.go.tmpl
  apis/supervisor/config/v1alpha1/types_oidcprovider.go.tmpl
  deploy/concierge/authentication.concierge.pinniped.dev_webhookauthenticators.yaml
  deploy/concierge/config.concierge.pinniped.dev_credentialissuers.yaml
  deploy/supervisor/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/concierge/authentication/v1alpha1/types_webhook.go
  generated/1.17/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.17/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.17/crds/authentication.concierge.pinniped.dev_webhookauthenticators.yaml
  generated/1.17/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.17/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/concierge/authentication/v1alpha1/types_webhook.go
  generated/1.18/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.18/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.18/crds/authentication.concierge.pinniped.dev_webhookauthenticators.yaml
  generated/1.18/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.18/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/concierge/authentication/v1alpha1/types_webhook.go
  generated/1.19/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.19/apis/supervisor/config/v1alpha1/types_oidcprovider.go
  generated/1.19/crds/authentication.concierge.pinniped.dev_webhookauthenticators.yaml
  generated/1.19/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.19/crds/config.supervisor.pinniped.dev_oidcproviders.yaml
  test/integration/kube_api_discovery_test.go
Labels: cla-not-required

#206 Supervisor authorize endpoint reuses existing CSRF cookies and signs new ones
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/provider/manager/manager.go
Labels: cla-not-required

#212 Reduce client cert TTL back to 5 mins
  internal/certauthority/certauthority.go
  internal/certauthority/certauthority_test.go
  internal/registry/credentialrequest/rest.go
  internal/registry/credentialrequest/rest_test.go
  test/integration/client_test.go
  test/integration/concierge_credentialrequest_test.go
Labels: cla-not-required

#209 Fix broken links in the project's website
  site/content/docs/architecture.md
  site/content/docs/scope.md
Labels: cla-not-required

#213 Add our TokenCredentialRequest to the "pinniped" API category as well.
  internal/registry/credentialrequest/rest.go
  internal/registry/credentialrequest/rest_test.go
  test/integration/kube_api_discovery_test.go
Labels: cla-not-required

#215 Fix some issues in the UpstreamOIDCProvider CRD and controller
  apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go.tmpl
  deploy/supervisor/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.17/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.17/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.18/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.18/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.19/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.19/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  test/integration/supervisor_upstream_test.go
Labels: cla-not-required

#220 Fix landing page use cases
  site/themes/pinniped/layouts/partials/use-cases.html
Labels: cla-not-required

#219 Convert CLI tests to work through an HTTP forward proxy.
  hack/prepare-for-integration-tests.sh
  test/deploy/dex/dex.yaml
  test/deploy/dex/proxy.yaml
  test/deploy/dex/values.yaml
  test/integration/cli_test.go
  test/library/env.go
Labels: cla-not-required, go

#221 Add support for custom CA bundle in CLI and UpstreamOIDCProvider.
  .golangci.yaml
  apis/supervisor/idp/v1alpha1/types_tls.go.tmpl
  apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go.tmpl
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  deploy/supervisor/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/supervisor/idp/v1alpha1/types_tls.go
  generated/1.17/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.17/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/supervisor/idp/v1alpha1/types_tls.go
  generated/1.18/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.18/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/supervisor/idp/v1alpha1/types_tls.go
  generated/1.19/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.19/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/idp.supervisor.pinniped.dev_upstreamoidcproviders.yaml
  hack/prepare-for-integration-tests.sh
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  internal/oidcclient/login.go
  internal/oidcclient/login_test.go
  test/deploy/dex/dex.yaml
  test/integration/cli_test.go
  test/integration/supervisor_upstream_test.go
  test/library/env.go
Labels: cla-not-required

#222 Re-add the TestSupervisorLogin integration test.
  test/integration/supervisor_login_test.go
Labels: cla-not-required, go

#223 Refactor certificate generation for integration test Dex.
  hack/lib/tilt/Tiltfile
  hack/prepare-for-integration-tests.sh
  test/deploy/dex/cert-issuer.yaml
  test/deploy/dex/dex.yaml
Labels: cla-not-required

#224 Move `./internal/oidcclient` to `./pkg/oidcclient`.
  Dockerfile
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/provider/manager/manager.go
  pkg/oidcclient/filesession/cachefile.go
  pkg/oidcclient/filesession/cachefile_test.go
  pkg/oidcclient/filesession/filesession.go
  pkg/oidcclient/filesession/filesession_test.go
  pkg/oidcclient/filesession/testdata/invalid.yaml
  pkg/oidcclient/filesession/testdata/valid.yaml
  pkg/oidcclient/filesession/testdata/wrong-version.yaml
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  pkg/oidcclient/nonce/nonce.go
  pkg/oidcclient/nonce/nonce_test.go
  pkg/oidcclient/pkce/pkce.go
  pkg/oidcclient/pkce/pkce_test.go
  pkg/oidcclient/state/state.go
  pkg/oidcclient/state/state_test.go
  pkg/oidcclient/types.go
  test/integration/cli_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required, go

#226 Fix demo.md and update default namespace for pinniped concierge.
  cmd/pinniped/cmd/get_kubeconfig.go
  cmd/pinniped/cmd/get_kubeconfig_test.go
  doc/demo.md
Labels: cla-not-required

#230 Add nonroot SCC to work on OpenShift clusters
  deploy/concierge/rbac.yaml
Labels: cla-not-required

#227 Use `omitempty` on UpstreamOIDCProvider `spec.authorizationConfig` field.
  apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go.tmpl
  generated/1.17/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.18/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  generated/1.19/apis/supervisor/idp/v1alpha1/types_upstreamoidcprovider.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_upstream_test.go
Labels: cla-not-required

#231 Add kube based storage for use with fosite
  go.mod
  internal/crud/crud.go
  internal/crud/crud_test.go
  internal/fosite/authorizationcode/authorizationcode.go
  internal/fosite/authorizationcode/authorizationcode_test.go
  test/integration/storage_test.go
Labels: cla-not-required

#233 Temporarily disable max inflight checks for mutating requests
  internal/concierge/server/server.go
Labels: cla-not-required

#232 Split test environment variables so there's a specific supervisor upstream client.
  hack/prepare-for-integration-tests.sh
  test/deploy/dex/dex.yaml
  test/integration/cli_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_upstream_test.go
  test/library/env.go
Labels: cla-not-required

#239 Set defaults for fosite config
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
Labels: cla-not-required

#245 Run TestSupervisorLogin only on valid HTTP/HTTPS supervisor addresses
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#246 Tweak some stdlib usage so we compile under Go 1.14.
  internal/fosite/authorizationcode/authorizationcode_test.go
  internal/testutil/tempdir.go
  internal/testutil/tempdir_go1.14.go
  pkg/oidcclient/filesession/cachefile_test.go
  pkg/oidcclient/filesession/filesession_test.go
  test/integration/cli_test.go
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required
