Repository vmware-tanzu/pinniped, pull requests merged in 2021-02, with the labels that each got.

#375 Add Codecov configuration file.
  .github/codecov.yml
Labels: chore, cla-not-required

#376 Add some trivial unit tests to internal/oidc/csrftoken.
  internal/oidc/csrftoken/csrftoken_test.go
Labels: cla-not-required

#383 Avoid double registering types in server scheme
  internal/concierge/server/server.go
  internal/concierge/server/server_test.go
Labels: cla-not-required

#325 Add an integration test helper to assert that no pods restart during the test
  test/integration/cli_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_client_test.go
  test/integration/concierge_credentialissuerconfig_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/concierge_kubecertagent_test.go
  test/integration/e2e_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_healthz_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_secrets_test.go
  test/integration/supervisor_upstream_test.go
  test/library/assertions.go
Labels: cla-not-required

#387 Add a v0.5.0 "multiple Pinnipeds" blog post.
  site/content/posts/multiple-pinnipeds.md
  site/redirects/go.pinniped.dev/netlify.toml
Labels: cla-not-required, website

#385 Use custom suffix in `Spec.Authenticator.APIGroup` of `TokenCredentialRequest`
  internal/concierge/server/server.go
  internal/controller/authenticator/authncache/cache.go
  internal/controller/authenticator/authncache/cache_test.go
  internal/controller/authenticator/cachecleaner/cachecleaner_test.go
  internal/controller/authenticator/jwtcachefiller/jwtcachefiller_test.go
  internal/controller/authenticator/webhookcachefiller/webhookcachefiller_test.go
  internal/groupsuffix/groupsuffix.go
  internal/groupsuffix/groupsuffix_test.go
  pkg/conciergeclient/conciergeclient.go
  pkg/conciergeclient/conciergeclient_test.go
  test/library/client.go
Labels: cla-not-required

#392 deploy/concierge: add RBAC for flowschemas and prioritylevelconfigurations
  deploy/concierge/rbac.yaml
Labels: cla-not-required

#393 Add no-op list support to token credential request
  internal/concierge/apiserver/apiserver.go
  internal/registry/credentialrequest/rest.go
  internal/registry/credentialrequest/rest_test.go
  test/integration/category_test.go
  test/integration/kube_api_discovery_test.go
Labels: cla-not-required

#395 Remove multierror package and migrate callers to k8s.io/apimachinery/pkg/util/errors.NewAggregate
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static_test.go
  internal/config/concierge/config_test.go
  internal/config/supervisor/config_test.go
  internal/controller/supervisorconfig/federation_domain_watcher.go
  internal/controller/supervisorconfig/federation_domain_watcher_test.go
  internal/groupsuffix/groupsuffix.go
  internal/groupsuffix/groupsuffix_test.go
  internal/multierror/multierror.go
  internal/multierror/multierror_test.go
  internal/testutil/fakekubeapi/fakekubeapi.go
  pkg/conciergeclient/conciergeclient_test.go
Labels: cla-not-required

#399 Upgrade Go from 1.15.7 to 1.15.8.
  Dockerfile
Labels: cla-not-required

#394 Use server scheme to handle credential request API group changes
  internal/concierge/server/server.go
  internal/concierge/server/server_test.go
  internal/controller/authenticator/authncache/cache.go
  internal/controller/authenticator/authncache/cache_test.go
  internal/controller/authenticator/cachecleaner/cachecleaner_test.go
  internal/controller/authenticator/jwtcachefiller/jwtcachefiller_test.go
  internal/controller/authenticator/webhookcachefiller/webhookcachefiller_test.go
Labels: cla-not-required

#404 cmd/pinniped: delete get-kubeconfig + exchange-token
  cmd/pinniped/cmd/deprecated.go
  cmd/pinniped/cmd/root.go
  test/integration/cli_test.go
Labels: cla-not-required

#407 test/integration: make TestKubeCertAgent more stable
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required

#390 Use middleware to mutate TokenCredentialRequest.Spec.Authenticator.APIGroup
  internal/groupsuffix/groupsuffix.go
  internal/groupsuffix/groupsuffix_test.go
  internal/kubeclient/kubeclient_test.go
  internal/kubeclient/middleware.go
  internal/kubeclient/middleware_test.go
  internal/kubeclient/verb_test.go
  internal/ownerref/ownerref.go
  internal/ownerref/ownerref_test.go
  internal/plog/klog.go
  internal/testutil/roundtrip.go
  pkg/conciergeclient/conciergeclient.go
  pkg/conciergeclient/conciergeclient_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_credentialrequest_test.go
  test/library/client.go
Labels: cla-not-required

#409 Upgrade Debian base images from 10.7 to 10.8.
  Dockerfile
  hack/lib/tilt/Tiltfile
  hack/lib/tilt/concierge.Dockerfile
  hack/lib/tilt/local-user-authenticator.Dockerfile
  hack/lib/tilt/supervisor.Dockerfile
  test/deploy/dex/proxy.yaml
Labels: cla-not-required, dependencies

#426 Tweak website styles for accessibility.
  site/resources/_gen/assets/scss/scss/site.scss_8967e03afb92eb0cac064520bf021ba2.content
  site/themes/pinniped/assets/scss/_base.scss
  site/themes/pinniped/assets/scss/_components.scss
  site/themes/pinniped/assets/scss/_variables.scss
  site/themes/pinniped/layouts/partials/footer.html
Labels: cla-not-required, enhancement, website

#431 concierge API service: update groupPriorityMinimum and versionPriority
  deploy/concierge/deployment.yaml
Labels: cla-not-required

#435 Bump Kube deps to v0.20.4
  generated/1.20/apis/go.mod
  generated/1.20/apis/go.sum
  generated/1.20/client/go.mod
  generated/1.20/client/go.sum
  go.mod
  go.sum
  hack/lib/kube-versions.txt
Labels: cla-not-required

#443 Restructure website documentation
  CONTRIBUTING.md
  README.md
  SCOPE.md
  deploy/concierge/README.md
  deploy/supervisor/README.md
  site/config.yaml
  site/content/community/_index.html
  site/content/docs/_index.md
  site/content/docs/background/_index.md
  site/content/docs/background/architecture.md
  site/content/docs/demo.md
  site/content/docs/howto/_index.md
  site/content/docs/howto/configure-concierge-jwt.md
  site/content/docs/howto/configure-concierge-webhook.md
  site/content/docs/howto/configure-supervisor.md
  site/content/docs/howto/install-cli.md
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
  site/content/docs/install.md
  site/content/docs/reference/_index.md
  site/content/docs/reference/api.md
  site/content/docs/reference/cli.md
  site/content/docs/reference/supported-clusters.md
  site/content/docs/scope.md
  site/content/docs/tutorials/_index.md
  site/content/docs/tutorials/concierge-and-supervisor-demo.md
  site/content/docs/tutorials/concierge-only-demo.md
  site/content/posts/multiple-pinnipeds.md
  site/netlify.toml
  site/resources/_gen/assets/scss/scss/site.scss_8967e03afb92eb0cac064520bf021ba2.content
  site/themes/pinniped/assets/scss/_base.scss
  site/themes/pinniped/assets/scss/_components.scss
  site/themes/pinniped/layouts/_default/docs.html
  site/themes/pinniped/layouts/partials/docs-sidebar.html
  site/themes/pinniped/layouts/shortcodes/buttonicon.html
  site/themes/pinniped/layouts/shortcodes/buttonlink.html
  site/themes/pinniped/layouts/shortcodes/dangernote.html
  site/themes/pinniped/layouts/shortcodes/docsmenu.html
  site/themes/pinniped/static/img/alert-circle-outline.svg
  site/themes/pinniped/static/img/download.png
Labels: cla-not-required

#446 More website tweaks.
  site/config.yaml
  site/content/community/_index.html
  site/content/posts/a-seal-of-approval.md
  site/redirects/get.pinniped.dev/netlify.toml
  site/resources/_gen/assets/scss/scss/site.scss_8967e03afb92eb0cac064520bf021ba2.content
  site/themes/pinniped/assets/scss/_components.scss
  site/themes/pinniped/layouts/_default/baseof.html
  site/themes/pinniped/layouts/_default/posts.html
  site/themes/pinniped/layouts/_default/section.html
  site/themes/pinniped/layouts/_default/single.html
  site/themes/pinniped/layouts/_default/tag.html
  site/themes/pinniped/layouts/index.html
  site/themes/pinniped/layouts/partials/blog-post-card.html
  site/themes/pinniped/layouts/partials/getting-started.html
  site/themes/pinniped/layouts/partials/hero.html
  site/themes/pinniped/layouts/partials/homepage-grid.html
  site/themes/pinniped/layouts/partials/team.html
  site/themes/pinniped/layouts/partials/use-cases.html
  site/themes/pinniped/static/img/margo-crawford.png
  site/themes/pinniped/static/img/nanci-lancaster.png
Labels: cla-not-required, enhancement, website

#447 Add security headers to the website.
  site/netlify.toml
  site/themes/pinniped/layouts/partials/header.html
  site/themes/pinniped/static/js/main.js
Labels: website

#453 Bump a bunch of minor dependencies.
  go.mod
  go.sum
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
Labels: cla-not-required, dependencies, go
