Repository vmware-tanzu/pinniped, pull requests merged in 2021-07, with the labels that each got.

#689 Extract some trivial helpers for identical code usages
  internal/oidc/auth/auth_handler.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/downstreamsession/downstream_session.go
Labels: cla-not-required

#701 Add `https_proxy` and `no_proxy` settings for the Supervisor
  deploy/supervisor/deployment.yaml
  deploy/supervisor/values.yaml
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher.go
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher_test.go
Labels: cla-not-required

#702 Fix broken upstream OIDC discovery timeout added in previous commit
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher.go
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher_test.go
  test/integration/concierge_api_serving_certs_test.go
Labels: cla-not-required

#703 Run the LDAP client's integration tests only on Kind
  test/cluster_capabilities/aks.yaml
  test/cluster_capabilities/eks.yaml
  test/cluster_capabilities/gke.yaml
  test/cluster_capabilities/kind.yaml
  test/cluster_capabilities/tkgs.yaml
  test/integration/ldap_client_test.go
  test/testlib/env.go
Labels: cla-not-required

#684 Add IPv6 support to FederationDomain spec.issuer field.
  internal/controller/supervisorconfig/tls_cert_observer.go
  internal/controller/supervisorconfig/tls_cert_observer_test.go
  pkg/oidcclient/login.go
Labels: cla-not-required

#706 Fix typo in generated API docs (s/mode/type/).
  apis/concierge/config/v1alpha1/types_credentialissuer.go.tmpl
  deploy/concierge/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.17/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.18/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.19/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.20/README.adoc
  generated/1.20/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.20/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/latest/apis/concierge/config/v1alpha1/types_credentialissuer.go
Labels: bug, cla-not-required

#705 Make TestImpersonationProxy less flaky.
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required, test-flake

#687 Add support for "response_mode=form_post" in Supervisor and CLI.
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  go.mod
  go.sum
  internal/httputil/securityheader/securityheader.go
  internal/httputil/securityheader/securityheader_test.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/clientregistry/clientregistry.go
  internal/oidc/clientregistry/clientregistry_test.go
  internal/oidc/discovery/discovery_handler.go
  internal/oidc/discovery/discovery_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/formposthtml/form_post.css
  internal/oidc/provider/formposthtml/form_post.gohtml
  internal/oidc/provider/formposthtml/form_post.js
  internal/oidc/provider/formposthtml/formposthtml.go
  internal/oidc/provider/formposthtml/formposthtml_test.go
  internal/testutil/assertions.go
  internal/testutil/oidctestutil/oidctestutil.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  test/integration/cli_test.go
  test/integration/e2e_test.go
  test/integration/formposthtml_test.go
  test/integration/supervisor_discovery_test.go
  test/testlib/assertions.go
  test/testlib/browsertest/browsertest.go
  test/testlib/client.go
Labels: cla-not-required

#707 Fix TestCLILoginOIDC when running against Okta, and lower CLI server shutdown timeout.
  pkg/oidcclient/login.go
  test/integration/cli_test.go
Labels: cla-not-required

#704 Make TestAPIServingCertificateAutoCreationAndRotation less flaky.
  test/integration/concierge_api_serving_certs_test.go
Labels: cla-not-required, test-flake

#711 Clear the browser cookies between each TestE2EFullIntegration subtest
  test/integration/e2e_test.go
Labels: cla-not-required

#714 ytt install docs suggest that you checkout the release tag
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
Labels: cla-not-required

#718 TestAgentController unit test is flaky, try to add workaround
  internal/controller/kubecertagent/kubecertagent_test.go
Labels: cla-not-required

#721 wait for lb dns to resolve in the impersonation proxy integration test
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#724 Copy .git dir during Docker build; used to bake git sha into binary
  .dockerignore
Labels: cla-not-required

#731 Removed Andrew Keesler, Pablo Schumaker from site, moved them to emeritus status on maintainers file,
  MAINTAINERS.md
  site/themes/pinniped/layouts/partials/team.html
  site/themes/pinniped/static/img/Anjali-Telang.png
  site/themes/pinniped/static/img/andrew-keesler.png
  site/themes/pinniped/static/img/pablo-schuhmacher.png
Labels: cla-not-required

#733 Switch to GHCR tools images for local tests, with `imagePullPolicy: IfNotPresent`.
  test/deploy/tools/cert-issuer.yaml
  test/deploy/tools/dex.yaml
  test/deploy/tools/ldap.yaml
  test/deploy/tools/proxy.yaml
  test/deploy/tools/values.yaml
Labels: cla-not-required

#741 dockerignore gets same contents as gitignore
  .dockerignore
  .gitignore
Labels: cla-not-required

#730 LDAP logins via CLI read from `PINNIPED_USERNAME` and `PINNIPED_PASSWORD` env vars
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  site/content/docs/howto/_index.md
  site/content/docs/howto/configure-concierge-jwt.md
  site/content/docs/howto/configure-concierge-supervisor-jwt.md
  site/content/docs/howto/configure-concierge-webhook.md
  site/content/docs/howto/configure-supervisor-with-gitlab.md
  site/content/docs/howto/configure-supervisor-with-jumpcloudldap.md
  site/content/docs/howto/configure-supervisor-with-okta.md
  site/content/docs/howto/configure-supervisor-with-openldap.md
  site/content/docs/howto/configure-supervisor.md
  site/content/docs/howto/install-cli.md
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
  site/content/docs/howto/login.md
  test/integration/e2e_test.go
Labels: cla-not-required

#742 Bump to Go 1.16.6 and Kube v0.21.3
  Dockerfile
  go.mod
  go.sum
Labels: cla-not-required

#739 Carefully merge desired annotations into impersonation proxy Service
  internal/controller/impersonatorconfig/impersonator_config.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#746 Fix CLI compilation on Windows.
  pkg/oidcclient/login.go
Labels: bug, cla-not-required

#748 Fix form_post CSS styling in Firefox and Safari.
  internal/oidc/provider/formposthtml/form_post.css
  internal/oidc/provider/formposthtml/formposthtml_test.go
Labels: cla-not-required

#747 certs_expirer: be specific about what secret to delete
  internal/controller/apicerts/certs_expirer.go
  internal/controller/apicerts/certs_expirer_test.go
Labels: cla-not-required

#752 Add ClusterIP service to impersonator-config-controller informer.
  internal/controller/impersonatorconfig/impersonator_config.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
Labels: bug, cla-not-required

#753 Fix backwards condition in E2E test assertion.
  test/integration/e2e_test.go
Labels: cla-not-required

#754 Relax the timeout for TestLegacyPodCleaner a bit.
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required, test-flake

#757 concierge_impersonation_proxy_test: check all forms of DNS
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#755 Update installation documentation
  site/config.yaml
  site/content/docs/howto/configure-supervisor.md
  site/content/docs/howto/install-cli.md
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
  site/content/docs/tutorials/concierge-and-supervisor-demo.md
  site/content/docs/tutorials/concierge-only-demo.md
  site/themes/pinniped/layouts/shortcodes/buttonlink.html
  site/themes/pinniped/layouts/shortcodes/latestversion.html
Labels: cla-not-required, documentation, website

#758 Fix broken TTY after manual auth code prompt.
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  test/integration/e2e_test.go
Labels: bug, cla-not-required

#760 Add v0.10.0 blog post.
  site/content/posts/2021-07-30-supporting-remote-oidc-workflows.md
Labels: cla-not-required, website
