Repository vmware-tanzu/pinniped, pull requests merged in 2021-05, with the labels that each got.

#595 Fix PSP-related regression since kube-cert-agent change in #569.
  deploy/concierge/deployment.yaml
  deploy/concierge/rbac.yaml
  internal/config/concierge/config.go
  internal/config/concierge/config_test.go
  internal/config/concierge/types.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/controllermanager/prepare_controllers.go
Labels: bug, cla-not-required

#598 supervisor gc: use singleton queue
  internal/controller/supervisorstorage/garbage_collector.go
  internal/controller/supervisorstorage/garbage_collector_test.go
  test/integration/supervisor_storage_garbage_collection_test.go
Labels: cla-not-required

#560 Client debug logging
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static.go
  cmd/pinniped/cmd/login_static_test.go
  internal/plog/plog.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  test/integration/cli_test.go
Labels: cla-not-required

#599 Do some minor copyediting on "configure-supervisor-with-gitlab.md".
  site/content/docs/howto/configure-supervisor-with-gitlab.md
Labels: cla-not-required, documentation

#602 Change access token storage lifetime to be the same as the refresh token's
  internal/oidc/oidc.go
  internal/oidc/token/token_handler_test.go
Labels: cla-not-required

#606 upstreamwatcher: preserve oidc discovery error
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  test/integration/supervisor_upstream_test.go
Labels: cla-not-required

#607 Fix TestImpersonationProxy on EKS.
  test/integration/concierge_impersonation_proxy_test.go
Labels: bug, cla-not-required

#608 upstreamwatcher: do not truncate explicit oidc errors
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher_test.go
  test/integration/supervisor_upstream_test.go
Labels: cla-not-required

#609 impersonation proxy test: handle admin users with UID such as on EKS
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#589 WIP: Support for Supervisor upstream LDAP IDPs in `pinniped get kubeconfig`
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  go.mod
  go.sum
  internal/oidc/discovery/discovery_handler.go
  internal/oidc/discovery/discovery_handler_test.go
  internal/oidc/idpdiscovery/idp_discovery_handler.go
  internal/oidc/idpdiscovery/idp_discovery_handler_test.go
  internal/oidc/oidc.go
  internal/oidc/provider/manager/manager.go
  internal/oidc/provider/manager/manager_test.go
  internal/testutil/ioutil.go
  test/integration/e2e_test.go
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required

#614 Tests for garbage collection behavior for access and refresh tokens
  internal/oidc/token/token_handler_test.go
  test/integration/e2e_test.go
Labels: cla-not-required

#594 cred req: disallow lossy user info translations
  cmd/local-user-authenticator/main.go
  cmd/local-user-authenticator/main_test.go
  internal/registry/credentialrequest/rest.go
  internal/registry/credentialrequest/rest_test.go
Labels: cla-not-required

#627 Create CredentialIssuer at install, not runtime.
  deploy/concierge/deployment.yaml
  internal/controller/issuerconfig/update_strategy.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/controllermanager/prepare_controllers.go
  test/integration/concierge_credentialissuer_test.go
Labels: cla-not-required

#618 Initial support for upstream LDAP group membership
  apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go.tmpl
  deploy/supervisor/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.17/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.18/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.19/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.20/README.adoc
  generated/1.20/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.20/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  generated/1.20/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/latest/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/latest/apis/supervisor/idp/v1alpha1/zz_generated.deepcopy.go
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher.go
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher_test.go
  internal/mocks/mockldapconn/mockldapconn.go
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/integration/e2e_test.go
  test/integration/ldap_client_test.go
  test/integration/supervisor_login_test.go
  test/library/env.go
Labels: cla-not-required

#620 Support `StartTLS` for `LDAPIdentityProvider`s
  hack/prepare-for-integration-tests.sh
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher.go
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher_test.go
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/deploy/tools/cert-issuer.yaml
  test/deploy/tools/ldap.yaml
  test/integration/ldap_client_test.go
  test/integration/supervisor_login_test.go
  test/library/client.go
  test/library/env.go
Labels: cla-not-required

#630 Upgrade Go module dependencies
  go.mod
  go.sum
Labels: cla-not-required, dependencies, go

#631 Stop generating zz_generated.openapi.go files.
  generated/1.17/client/concierge/openapi/zz_generated.openapi.go
  generated/1.17/client/go.mod
  generated/1.17/client/go.sum
  generated/1.18/client/concierge/openapi/zz_generated.openapi.go
  generated/1.18/client/go.mod
  generated/1.18/client/go.sum
  generated/1.19/client/concierge/openapi/zz_generated.openapi.go
  generated/1.19/client/go.mod
  generated/1.19/client/go.sum
  generated/1.20/client/concierge/openapi/zz_generated.openapi.go
  generated/1.20/client/go.mod
  generated/1.20/client/go.sum
  generated/latest/client/concierge/openapi/zz_generated.openapi.go
  go.mod
  hack/lib/update-codegen.sh
Labels: cla-not-required

#616 Add doc for configuring the supervisor with okta
  site/content/docs/howto/configure-supervisor-with-okta.md
Labels: cla-not-required

#635 Replace all references to "a specific version" with v0.8.0.
  site/content/docs/howto/install-cli.md
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
  site/content/docs/tutorials/concierge-only-demo.md
Labels: cla-not-required, documentation

#632 Add another unit test for the LDAP client code
  internal/testutil/tlsserver.go
  internal/upstreamldap/upstreamldap_test.go
Labels: cla-not-required

#641 Backports and dependency upgrades for v0.4.3
  Dockerfile
  go.mod
  go.sum
  internal/oidc/oidc.go
Labels: cla-not-required

#640 Refactor "endpoint address" parsing code into shared package.
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher_test.go
  internal/endpointaddr/endpointaddr.go
  internal/endpointaddr/endpointaddr_test.go
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/integration/ldap_client_test.go
Labels: cla-not-required

#643 Add user search base to downstream subject for upstream LDAP
  internal/oidc/auth/auth_handler.go
  internal/oidc/auth/auth_handler_test.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/oidc/provider/dynamic_upstream_idp_provider.go
  internal/testutil/oidctestutil/oidctestutil.go
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/deploy/tools/ldap.yaml
  test/integration/ldap_client_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#647 Use base64 binary-encoded value as UID for LDAP
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/integration/ldap_client_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#646 Update values.yaml to include CredentialIssuer ImpersonationProxy spec.
  deploy/concierge/deployment.yaml
  deploy/concierge/values.yaml
  site/content/docs/howto/install-concierge.md
Labels: cla-not-required

#626 Add spec fields to Credentialissuer API to configure impersonation proxy behavior
  apis/concierge/config/v1alpha1/types_credentialissuer.go.tmpl
  deploy/concierge/config.concierge.pinniped.dev_credentialissuers.yaml
  deploy/concierge/deployment.yaml
  deploy/concierge/values.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.17/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.18/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.19/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.20/README.adoc
  generated/1.20/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.20/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.20/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/latest/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/latest/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  internal/concierge/impersonator/config.go
  internal/concierge/impersonator/config_test.go
  internal/concierge/impersonator/impersonator.go
  internal/config/concierge/config.go
  internal/config/concierge/config_test.go
  internal/config/concierge/types.go
  internal/controller/impersonatorconfig/impersonator_config.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
  internal/controller/issuerconfig/create_or_update_credential_issuer_config.go
  internal/controller/issuerconfig/create_or_update_credential_issuer_config_test.go
  internal/controller/issuerconfig/doc.go
  internal/controller/issuerconfig/issuerconfig.go
  internal/controller/issuerconfig/issuerconfig_test.go
  internal/controllermanager/prepare_controllers.go
  site/content/docs/howto/install-concierge.md
  test/integration/concierge_impersonation_proxy_test.go
  test/integration/kubeclient_test.go
Labels: cla-not-required

#649 Default `groupSearch.attributes.groupName` to "dn" instead of "cn" in LDAPIdentityProvider spec
  apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go.tmpl
  deploy/supervisor/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.17/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.18/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.19/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/1.20/README.adoc
  generated/1.20/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  generated/1.20/crds/idp.supervisor.pinniped.dev_ldapidentityproviders.yaml
  generated/latest/apis/supervisor/idp/v1alpha1/types_ldapidentityprovider.go
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/integration/e2e_test.go
  test/integration/ldap_client_test.go
Labels: cla-not-required

#650 In LDAP, do not log username until we know the user exists.
  internal/upstreamldap/upstreamldap.go
  internal/upstreamldap/upstreamldap_test.go
  test/integration/ldap_client_test.go
Labels: cla-not-required
