Repository vmware-tanzu/pinniped, pull requests merged in 2021-04, with the labels that each got.

#544 Add a blog post about the v0.7.0 release.
  site/content/posts/2020-11-12-a-seal-of-approval.md
  site/content/posts/2021-02-04-multiple-pinnipeds.md
  site/content/posts/2021-04-01-concierge-on-managed-clusters.md
  site/themes/pinniped/layouts/shortcodes/community.html
Labels: cla-not-required, website

#552 Generate more helpful context/cluster/user names in `pinniped get kubeconfig`
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/testdata/kubeconfig.yaml
  cmd/pinniped/cmd/whoami_test.go
Labels: cla-not-required, enhancement

#561 Added Ok amba logo for adopters file
  site/themes/pinniped/static/img/ok-amba.svg
Labels: cla-not-required

#562 Add cluster-specific credential caching to login subcommands.
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static.go
  cmd/pinniped/cmd/login_static_test.go
  internal/execcredcache/cachefile.go
  internal/execcredcache/cachefile_test.go
  internal/execcredcache/execcredcache.go
  internal/execcredcache/execcredcache_test.go
  internal/execcredcache/testdata/invalid.yaml
  internal/execcredcache/testdata/valid.yaml
  internal/execcredcache/testdata/wrong-version.yaml
  pkg/oidcclient/filesession/filesession.go
  pkg/oidcclient/filesession/filesession_test.go
Labels: cla-not-required, enhancement

#563 CLI cluster-specific credentials enhancements (followup to #562)
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static.go
  cmd/pinniped/cmd/login_static_test.go
  test/integration/cli_test.go
Labels: cla-not-required, enhancement

#565 Remove proxy-kubeconfig.yaml.
  proxy-kubeconfig.yaml
Labels: cla-not-required

#566 Upgrade to client-go and apimachinery from Kubernetes 1.21.0.
  go.mod
  go.sum
  internal/concierge/scheme/scheme_test.go
Labels: cla-not-required

#556 added search functionality to docs on Pinniped.dev
  public/categories/index.xml
  public/index.xml
  public/sitemap.xml
  public/tags/index.xml
  site/netlify.toml
  site/themes/pinniped/layouts/_default/baseof.html
  site/themes/pinniped/layouts/partials/docs-sidebar.html
Labels: cla-not-required

#570 Add OK a.m.b.a. to adopters.md file
  ADOPTERS.md
Labels: cla-not-required

#579 internal/kubeclient: match plog level with klog level
  internal/kubeclient/copied.go
Labels: cla-not-required

#580 Bug fixes and dependency bumps for v0.4.x release branch.
  Dockerfile
  generated/1.20/apis/go.mod
  generated/1.20/apis/go.sum
  generated/1.20/client/go.mod
  generated/1.20/client/go.sum
  go.mod
  go.sum
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/deleter_test.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required

#581 Fix some small issues from #580 discovered in CI
  generated/1.20/apis/go.mod
  generated/1.20/apis/go.sum
  generated/1.20/client/go.mod
  generated/1.20/client/go.sum
  go.sum
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/deleter_test.go
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required

#578 Remove unneeded sleeps in TestE2EFullIntegration and jwtcachefiller tests.
  internal/controller/authenticator/jwtcachefiller/jwtcachefiller_test.go
  test/integration/e2e_test.go
Labels: cla-not-required

#582 Adjust "/bin/killall sleep" in new test to be less flaky in CI.
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required, test-flake

#576 hack: add prepare-webhook-on-kind.sh
  hack/prepare-webhook-on-kind.sh
Labels: cla-not-required

#569 Refactor kube-cert-agent controllers to use a Deployment.
  deploy/concierge/rbac.yaml
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/annotater_test.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/creater_test.go
  internal/controller/kubecertagent/deleter.go
  internal/controller/kubecertagent/deleter_test.go
  internal/controller/kubecertagent/execer.go
  internal/controller/kubecertagent/execer_test.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/controller/kubecertagent/legacypodcleaner.go
  internal/controller/kubecertagent/legacypodcleaner_test.go
  internal/controller/kubecertagent/mocks/generate.go
  internal/controller/kubecertagent/mocks/mockdynamiccert.go
  internal/controller/kubecertagent/mocks/mockpodcommandexecutor.go
  internal/controller/kubecertagent/pod_command_executor.go
  internal/controllermanager/prepare_controllers.go
  test/integration/concierge_credentialissuer_test.go
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required

#584 Fix a broken docs link in our README.
  README.md
Labels: cla-not-required, documentation

#588 webhookcachefiller: be stricter about CA bundle validation
  internal/controller/authenticator/authenticator.go
  internal/controller/authenticator/webhookcachefiller/webhookcachefiller_test.go
Labels: cla-not-required

#590 impersonator: add support for service account token authentication
  internal/concierge/impersonator/doc.go
  internal/concierge/impersonator/impersonator.go
  internal/concierge/impersonator/impersonator_test.go
  internal/controller/authenticator/authncache/cache.go
  internal/valuelesscontext/valuelesscontext.go
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#592 valuelesscontext: make unit tests more clear
  internal/valuelesscontext/valuelesscontext_test.go
Labels: cla-not-required

#587 Added documentation for how to configure the Supervisor with GitLab
  site/content/docs/howto/configure-supervisor-with-gitlab.md
Labels: cla-not-required
