Repository vmware-tanzu/pinniped, pull requests merged in 2021-03, with the labels that each got.

#467 Fix missing titles on website docs.
  site/config.yaml
  site/content/docs/_index.md
  site/content/docs/background/_index.md
  site/content/docs/reference/_index.md
  site/content/docs/tutorials/_index.md
Labels: bug, cla-not-required, documentation, website

#466 Upgrade Go and Go library dependencies.
  Dockerfile
  go.mod
  go.sum
  internal/mocks/credentialrequestmocks/credentialrequestmocks.go
  internal/mocks/mockkeyset/mockkeyset.go
  internal/mocks/mocksecrethelper/mocksecrethelper.go
  internal/mocks/mocktokenauthenticator/mocktokenauthenticator.go
  internal/mocks/mocktokenauthenticatorcloser/mocktokenauthenticatorcloser.go
  internal/mocks/mockupstreamoidcidentityprovider/mockupstreamoidcidentityprovider.go
  internal/oidc/token_exchange.go
Labels: cla-not-required, dependencies, docker, go

#469 Factor out issuerconfig.UpdateStrategy helper.
  internal/controller/issuerconfig/update_strategy.go
  internal/controller/issuerconfig/update_strategy_test.go
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/creater.go
  internal/controller/kubecertagent/execer.go
  internal/controller/kubecertagent/kubecertagent.go
Labels: cla-not-required

#471 Deprecate status.kubeConfigInfo field in CredentialIssuer and move this data into strategies field.
  apis/concierge/config/v1alpha1/types_credentialissuer.go.tmpl
  deploy/concierge/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.17/README.adoc
  generated/1.17/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.17/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.17/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.18/README.adoc
  generated/1.18/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.18/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.18/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.19/README.adoc
  generated/1.19/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.19/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.19/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/1.20/README.adoc
  generated/1.20/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/1.20/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  generated/1.20/crds/config.concierge.pinniped.dev_credentialissuers.yaml
  generated/latest/apis/concierge/config/v1alpha1/types_credentialissuer.go
  generated/latest/apis/concierge/config/v1alpha1/zz_generated.deepcopy.go
  go.sum
  internal/controller/issuerconfig/kube_config_info_publisher.go
  internal/controller/issuerconfig/kube_config_info_publisher_test.go
  internal/controller/issuerconfig/update_strategy.go
  internal/controller/issuerconfig/update_strategy_test.go
  internal/controller/kubecertagent/annotater.go
  internal/controller/kubecertagent/annotater_test.go
  internal/controller/kubecertagent/creater_test.go
  internal/controller/kubecertagent/execer.go
  internal/controller/kubecertagent/execer_test.go
  internal/controller/kubecertagent/kubecertagent.go
  internal/controllermanager/prepare_controllers.go
  test/integration/concierge_credentialissuer_test.go
Labels: cla-not-required

#472 Make TestGetPinnipedCategory and TestKubeClientOwnerRef tests more resilient.
  test/integration/category_test.go
  test/integration/kubeclient_test.go
Labels: cla-not-required, test-flake

#473 oidc discovery: encode metadata once and reuse
  internal/oidc/discovery/discovery_handler.go
Labels: cla-not-required

#478 Fix hack/prepare-for-integration-tests.sh for MacOS Big Sur
  hack/prepare-for-integration-tests.sh
Labels: cla-not-required

#485 Create ROADMAP.md
  ROADMAP.md
Labels: cla-not-required

#488 Add retries to TestSupervisorTLSTerminationWithSNI and TestSupervisorOIDCDiscovery.
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required, test-flake

#495 Add golangci-lint to .pre-commit-config.yaml.
  .pre-commit-config.yaml
Labels: cla-not-required, enhancement

#497 Ignore test coverage for local-user-authenticator.
  .github/codecov.yml
Labels: cla-not-required

#500 Make TestAPIServingCertificateAutoCreationAndRotation more reliable.
  test/integration/concierge_api_serving_certs_test.go
Labels: cla-not-required

#501 Improve the reliability of TestGetPinnipedCategory.
  test/integration/category_test.go
Labels: cla-not-required, test-flake

#503 Rework integration test assertions for pod restarts.
  test/integration/cli_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_client_test.go
  test/integration/concierge_credentialissuer_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/concierge_kubecertagent_test.go
  test/integration/e2e_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_healthz_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_secrets_test.go
  test/integration/supervisor_upstream_test.go
  test/library/assertions.go
  test/library/dumplogs.go
  test/library/env.go
Labels: cla-not-required

#476 cmd/pinniped: add whoami cli command
  cmd/pinniped/cmd/kube_util.go
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/whoami.go
  cmd/pinniped/cmd/whoami_test.go
  test/integration/cli_test.go
  test/integration/e2e_test.go
Labels: cla-not-required

#505 Move to github.com/form3tech-oss/jwt-go
  go.mod
  go.sum
Labels: cla-not-required

#498 Impersonation proxy docs
  site/content/docs/background/architecture.md
  site/content/docs/reference/cli.md
  site/content/docs/reference/supported-clusters.md
  site/content/docs/tutorials/concierge-and-supervisor-demo.md
  site/content/docs/tutorials/concierge-only-demo.md
Labels: cla-not-required

#514 pinniped whoami: print correct cluster info when --kubeconfig-context is used
  cmd/pinniped/cmd/whoami.go
  cmd/pinniped/cmd/whoami_test.go
Labels: cla-not-required

#515 Upgrade Kubernetes runtime libraries to v1.20.5.
  go.mod
  go.sum
Labels: cla-not-required, dependencies, go

#516 Add CLI command for generating docs
  cmd/pinniped/cmd/generate_markdown_help.go
  go.sum
Labels: cla-not-required

#524 Allow running CLI-related integration tests with pre-built binary.
  test/library/cli.go
Labels: cla-not-required, test-flake

#525 Added kubeapps and vmware tanzu logos
  site/themes/pinniped/static/img/kubeapps.svg
  site/themes/pinniped/static/img/vmware-tanzu.svg
Labels: cla-not-required

#528 impersonation proxy: add RBAC to impersonate user extra and SAs
  deploy/concierge/rbac.yaml
Labels: cla-not-required

#531 Remove library.DumpLogs test helper.
  test/integration/e2e_test.go
  test/integration/supervisor_login_test.go
  test/library/assertions.go
  test/library/dumplogs.go
Labels: chore, cla-not-required

#517 Tweak some assertions in TestSupervisorOIDCDiscovery.
  test/integration/supervisor_discovery_test.go
Labels: cla-not-required, test-flake

#532 Update Google Group Link
  README.md
Labels: cla-not-required

#529 updated adopters.md instructions and included logos from VMware Tanzu…
  ADOPTERS.md
Labels: cla-not-required

#533 Add annotation to make the idle timeout be over 1 hour rather than 1 minute
  internal/controller/impersonatorconfig/impersonator_config.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
Labels: cla-not-required

#534 Deflake TestGetPinnipedCategory.
  test/integration/category_test.go
Labels: cla-not-required, test-flake

#536 Do not error when trying to delete the TLS secret and you get a not found
  internal/controller/impersonatorconfig/impersonator_config.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
Labels: cla-not-required

#542 Use "0.0.0" as our fake version instead of "?.?.?" to avoid a panic.
  hack/lib/version.sh
Labels: bug, cla-not-required

#540 Add hack/prepare-supervisor-on-kind.sh
  hack/prepare-for-integration-tests.sh
  hack/prepare-impersonator-on-kind.sh
  hack/prepare-supervisor-on-kind.sh
Labels: cla-not-required

#543 Fix missing "v".
  hack/lib/version.sh
Labels: bug, cla-not-required
