Repository vmware-tanzu/pinniped, pull requests merged in 2021-09, with the labels that each got.

#831 Add community info and resolve some minor issues
  site/content/posts/2021-08-27-supporting-ad-oidc-workflows.md
Labels: cla-not-required

#835 Fix broken "read only" fields added in v0.11.0.
  deploy/concierge/deployment.yaml
  deploy/supervisor/deployment.yaml
  hack/prepare-for-integration-tests.sh
Labels: bug, cla-not-required

#834 Add release note reference in the v0.11.0 Blog Post
  site/content/posts/2021-08-27-supporting-ad-oidc-workflows.md
Labels: cla-not-required

#837 So long and thanks for all the fish 🦭
  MAINTAINERS.md
  site/themes/pinniped/layouts/partials/team.html
  site/themes/pinniped/static/img/matt-moyer.png
Labels: documentation, cla-not-required, website

#836 Make sure search base in the validatedSettings cache is properly updated when the bind secret changes
  internal/controller/supervisorconfig/activedirectoryupstreamwatcher/active_directory_upstream_watcher.go
  internal/controller/supervisorconfig/activedirectoryupstreamwatcher/active_directory_upstream_watcher_test.go
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher.go
  internal/controller/supervisorconfig/ldapupstreamwatcher/ldap_upstream_watcher_test.go
  internal/controller/supervisorconfig/upstreamwatchers/upstream_watchers.go
  test/integration/supervisor_login_test.go
  test/testlib/client.go
Labels: cla-not-required

#839 Improve the selectors of Deployments and Services
  deploy/concierge/deployment.yaml
  deploy/concierge/helpers.lib.yaml
  deploy/concierge/rbac.yaml
  deploy/local-user-authenticator/deployment.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/helpers.lib.yaml
  deploy/supervisor/service.yaml
  hack/lib/kind-config/single-node.yaml
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/testutil/delete.go
  test/integration/concierge_kubecertagent_test.go
Labels: cla-not-required

#840 ran `go mod tidy`
  go.mod
Labels: cla-not-required

#842 kubecertagent: fix flakey tests
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
  internal/controller/kubecertagent/legacypodcleaner.go
  internal/controller/kubecertagent/legacypodcleaner_test.go
  internal/controllerinit/controllerinit.go
Labels: cla-not-required

#848 Tests use CertificatesV1 when available, otherwise use CertificatesV1beta1
  internal/testutil/kube_server_compatibility.go
  test/integration/concierge_impersonation_proxy_test.go
  test/integration/whoami_test.go
Labels: cla-not-required

#849 certauthority: tolerate larger clock skew between API server and pinniped
  internal/certauthority/certauthority.go
  internal/certauthority/certauthority_test.go
  internal/controller/impersonatorconfig/impersonator_config_test.go
Labels: cla-not-required

#846 kubecertagent: attempt to load signer as long as agent labels match
  internal/controller/kubecertagent/kubecertagent.go
  internal/controller/kubecertagent/kubecertagent_test.go
Labels: cla-not-required

#852 upstreamoidc: directly detect user info support
  internal/upstreamoidc/upstreamoidc.go
  internal/upstreamoidc/upstreamoidc_test.go
Labels: cla-not-required

#853 upstreamoidc: log claim keys at debug level
  internal/upstreamoidc/upstreamoidc.go
Labels: cla-not-required

#854 Do not truncate x509 errors
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher.go
  internal/controller/supervisorconfig/oidcupstreamwatcher/oidc_upstream_watcher_test.go
  test/integration/supervisor_upstream_test.go
Labels: cla-not-required
