Repository vmware-tanzu/pinniped, pull requests merged in 2021-06, with the labels that each got.

#652 In TestImpersonationProxy tests, avoid mutating anything in parallel block of tests.
  test/integration/concierge_impersonation_proxy_test.go
Labels: test-flake

#637 LDAP docs
  site/content/docs/howto/configure-concierge-jwt.md
  site/content/docs/howto/configure-concierge-supervisor-jwt.md
  site/content/docs/howto/configure-concierge-webhook.md
  site/content/docs/howto/configure-supervisor-with-gitlab.md
  site/content/docs/howto/configure-supervisor-with-jumpcloudldap.md
  site/content/docs/howto/configure-supervisor-with-okta.md
  site/content/docs/howto/configure-supervisor-with-openldap.md
  site/content/docs/howto/configure-supervisor.md
  site/content/docs/howto/install-supervisor.md
  site/content/posts/2021-05-31-first-ldap-release.md
Labels: cla-not-required

#653 Fix another impersonation test flake related to `kubectl logs --tail` line count + test refactor.
  test/integration/concierge_impersonation_proxy_test.go
Labels: test-flake

#655 Update docs for v0.9.0
  site/content/docs/howto/install-cli.md
  site/content/docs/howto/install-concierge.md
  site/content/docs/howto/install-supervisor.md
  site/content/docs/tutorials/concierge-only-demo.md
  site/content/posts/2021-06-02-first-ldap-release.md
Labels: documentation, website

#656 Remove an invalid test assertion in TestCredentialIssuer.
  test/integration/concierge_credentialissuer_test.go
Labels: cla-not-required, test-flake

#658 Tolerate NotFound when deleting services in `impersonatorconfig`.
  internal/controller/impersonatorconfig/impersonator_config.go
  test/integration/concierge_impersonation_proxy_test.go
Labels: bug, cla-not-required

#657 Avoid a rare flake in TestSupervisorLogin.
  test/integration/supervisor_login_test.go
Labels: cla-not-required, test-flake

#660 Fix typo in CredentialIssuer ytt template.
  deploy/concierge/deployment.yaml
  deploy/concierge/values.yaml
Labels: bug, cla-not-required

#662 Parameterize our test images in ytt.
  test/deploy/tools/cert-issuer.yaml
  test/deploy/tools/dex.yaml
  test/deploy/tools/ldap.yaml
  test/deploy/tools/proxy.yaml
  test/deploy/tools/values.yaml
Labels: cla-not-required, test-flake

#645 impersonator: honor anonymous authentication being disabled
  internal/concierge/impersonator/doc.go
  internal/concierge/impersonator/impersonator.go
  internal/concierge/impersonator/impersonator_test.go
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#665 impersonator: remove redundant deleteKnownImpersonationHeaders logic
  internal/concierge/impersonator/impersonator.go
  internal/concierge/impersonator/impersonator_test.go
Labels: cla-not-required

#667 impersonator: run as a distinct SA with minimal permissions
  deploy/concierge/deployment.yaml
  deploy/concierge/rbac.yaml
  internal/concierge/impersonator/impersonator.go
  test/integration/concierge_impersonation_proxy_test.go
  test/integration/rbac_test.go
Labels: cla-not-required

#670 impersonator: always authorize every request
  internal/concierge/impersonator/doc.go
  internal/concierge/impersonator/impersonator.go
  internal/concierge/impersonator/impersonator_test.go
  test/integration/concierge_impersonation_proxy_test.go
Labels: cla-not-required

#671 TestServiceAccountPermissions: handle extra permissions on EKS
  test/integration/rbac_test.go
Labels: cla-not-required

#673 Use a custom type for our static CLI client (smaller change).
  internal/fositestorage/accesstoken/accesstoken.go
  internal/fositestorage/accesstoken/accesstoken_test.go
  internal/fositestorage/authorizationcode/authorizationcode.go
  internal/fositestorage/authorizationcode/authorizationcode_test.go
  internal/fositestorage/fositestorage.go
  internal/fositestorage/openidconnect/openidconnect.go
  internal/fositestorage/openidconnect/openidconnect_test.go
  internal/fositestorage/pkce/pkce.go
  internal/fositestorage/pkce/pkce_test.go
  internal/fositestorage/refreshtoken/refreshtoken.go
  internal/fositestorage/refreshtoken/refreshtoken_test.go
  internal/oidc/clientregistry/clientregistry.go
  internal/oidc/clientregistry/clientregistry_test.go
  internal/oidc/kube_storage.go
  internal/oidc/nullstorage.go
  internal/oidc/nullstorage_test.go
  internal/oidc/oidc.go
Labels: cla-not-required

#674 Improve our integration test "Eventually" assertions.
  test/integration/category_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_client_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/concierge_impersonation_proxy_test.go
  test/integration/ldap_client_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_secrets_test.go
  test/integration/supervisor_storage_garbage_collection_test.go
  test/library/access.go
  test/library/assertions.go
  test/library/browsertest/browsertest.go
  test/library/client.go
Labels: cla-not-required, test-flake

#681 Fix bad test package name
  internal/controllerlib/test/integration/examplecontroller_test.go
  internal/dynamiccert/provider_test.go
  test/integration/category_test.go
  test/integration/cli_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/concierge_availability_test.go
  test/integration/concierge_client_test.go
  test/integration/concierge_credentialissuer_test.go
  test/integration/concierge_credentialrequest_test.go
  test/integration/concierge_impersonation_proxy_test.go
  test/integration/concierge_kubecertagent_test.go
  test/integration/concierge_kubectl_test.go
  test/integration/e2e_test.go
  test/integration/kube_api_discovery_test.go
  test/integration/kubeclient_test.go
  test/integration/ldap_client_test.go
  test/integration/rbac_test.go
  test/integration/supervisor_discovery_test.go
  test/integration/supervisor_healthz_test.go
  test/integration/supervisor_login_test.go
  test/integration/supervisor_secrets_test.go
  test/integration/supervisor_storage_garbage_collection_test.go
  test/integration/supervisor_storage_test.go
  test/integration/supervisor_upstream_test.go
  test/integration/whoami_test.go
  test/testlib/access.go
  test/testlib/assertions.go
  test/testlib/browsertest/browsertest.go
  test/testlib/cli.go
  test/testlib/client.go
  test/testlib/env.go
  test/testlib/iotest.go
  test/testlib/iplookup.go
  test/testlib/iplookup_go1.14.go
  test/testlib/skip.go
  test/testlib/spew.go
Labels: cla-not-required

#680 Update to Kubernetes 1.21.2 runtime components.
  go.mod
  go.sum
Labels: cla-not-required, dependencies, go

#683 credentialrequest: use safer approximation for ExpirationTimestamp
  internal/registry/credentialrequest/rest.go
Labels: cla-not-required
