Repository vmware-tanzu/pinniped, pull requests merged in 2021-01, with the labels that each got.

#311 Remove blockOwnerDeletion from the supervisor secrets
  internal/controller/supervisorconfig/generator/supervisor_secrets.go
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
Labels: cla-not-required

#313 Copyright year validation in linter and pre-commit hook
  .golangci.yaml
  .pre-commit-config.yaml
  .pre-commit-hooks.yaml
  hack/check-copyright-year.sh
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
Labels: cla-not-required

#312 test/integration: fix intermittent failures on GKE
  test/integration/concierge_credentialissuerconfig_test.go
Labels: cla-not-required

#314 Add kubernetes 1.20 to kube-versions.txt
  hack/lib/kube-versions.txt
Labels: cla-not-required

#316 Always set an owner ref back to our deployment
  cmd/local-user-authenticator/main.go
  cmd/pinniped-supervisor/main.go
  cmd/pinniped/cmd/kubeconfig.go
  deploy/concierge/deployment.yaml
  deploy/concierge/rbac.yaml
  internal/client/client.go
  internal/concierge/server/server.go
  internal/controller/supervisorconfig/generator/supervisor_secrets.go
  internal/controller/supervisorconfig/generator/supervisor_secrets_test.go
  internal/controllermanager/prepare_controllers.go
  internal/deploymentref/deploymentref.go
  internal/kubeclient/kubeclient.go
  internal/kubeclient/option.go
  internal/kubeclient/roundtrip.go
  internal/ownerref/ownerref.go
  internal/ownerref/ownerref_test.go
  pkg/conciergeclient/conciergeclient.go
  test/integration/kubeclient_test.go
Labels: cla-not-required

#318 Fetch claims from the user info endpoint if provided
  internal/upstreamoidc/upstreamoidc.go
  internal/upstreamoidc/upstreamoidc_test.go
Labels: cla-not-required

#322 Wire in new env vars for user info testing
  hack/prepare-for-integration-tests.sh
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  test/integration/e2e_test.go
  test/library/env.go
Labels: cla-not-required

#331 Update test/integration/kubeclient_test.go to work with Kube 1.20 GC behavior
  test/integration/kubeclient_test.go
  test/library/assertions.go
Labels: cla-not-required

#333 groups claim parsing
  internal/oidc/callback/callback_handler.go
  internal/oidc/callback/callback_handler_test.go
  internal/upstreamoidc/upstreamoidc.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#334 Fix an issue in TestE2EFullIntegration groups assertions.
  test/integration/e2e_test.go
Labels: bug, cla-not-required

#326 Run Tilt images as root for faster reload
  deploy/concierge/deployment.yaml
  deploy/concierge/values.yaml
  deploy/local-user-authenticator/deployment.yaml
  deploy/local-user-authenticator/values.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/values.yaml
  hack/lib/tilt/Tiltfile
Labels: cla-not-required

#344 Wire api group suffix through YTT/server components/CLI/integration tests
  cmd/pinniped-supervisor/main.go
  cmd/pinniped/cmd/deprecated.go
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/kubeconfig_test.go
  cmd/pinniped/cmd/login_oidc.go
  cmd/pinniped/cmd/login_oidc_test.go
  cmd/pinniped/cmd/login_static.go
  cmd/pinniped/cmd/login_static_test.go
  deploy/concierge/deployment.yaml
  deploy/concierge/helpers.lib.yaml
  deploy/concierge/rbac.yaml
  deploy/concierge/values.yaml
  deploy/concierge/z0_crd_overlay.yaml
  deploy/supervisor/deployment.yaml
  deploy/supervisor/helpers.lib.yaml
  deploy/supervisor/rbac.yaml
  deploy/supervisor/values.yaml
  deploy/supervisor/z0_crd_overlay.yaml
  internal/apigroup/apigroup.go
  internal/apigroup/apigroup_test.go
  internal/concierge/server/server.go
  internal/config/concierge/config.go
  internal/config/concierge/config_test.go
  internal/config/concierge/types.go
  internal/config/supervisor/config.go
  internal/config/supervisor/config_test.go
  internal/config/supervisor/types.go
  internal/controllermanager/prepare_controllers.go
  pkg/conciergeclient/conciergeclient.go
  pkg/conciergeclient/conciergeclient_test.go
  test/integration/cli_test.go
  test/integration/client_test.go
  test/integration/concierge_api_serving_certs_test.go
  test/integration/e2e_test.go
  test/integration/kube_api_discovery_test.go
  test/integration/kubeclient_test.go
  test/library/client.go
  test/library/env.go
Labels: cla-not-required

#327 Restore max in flight check when updating to 0.19.5 #243
  internal/concierge/server/server.go
Labels: cla-not-required

#342 Remove pre-commit hooks file to de-duplicate from pre-commit-config
  .pre-commit-hooks.yaml
Labels: cla-not-required

#347 Upgrade to github.com/coreos/go-oidc v3.0.0.
  cmd/pinniped/cmd/kubeconfig.go
  cmd/pinniped/cmd/login_oidc.go
  go.mod
  go.sum
  internal/controller/supervisorconfig/upstreamwatcher/upstreamwatcher.go
  internal/mocks/mockkeyset/generate.go
  internal/oidc/auth/auth_handler.go
  internal/oidc/callback/callback_handler.go
  internal/oidc/oidc.go
  internal/oidc/oidctestutil/oidc.go
  internal/oidc/token_exchange.go
  internal/upstreamoidc/upstreamoidc.go
  internal/upstreamoidc/upstreamoidc_test.go
  pkg/oidcclient/login.go
  pkg/oidcclient/login_test.go
  pkg/oidcclient/nonce/nonce.go
  pkg/oidcclient/nonce/nonce_test.go
  test/integration/e2e_test.go
  test/integration/supervisor_login_test.go
Labels: cla-not-required

#335 Optimize image build using .dockerignore and BuildKit features.
  .dockerignore
  Dockerfile
Labels: cla-not-required, enhancement

#365 Upgrade github.com/oleiade/reflections to v1.0.1.
  go.mod
  go.sum
Labels: cla-not-required

#369 Prune unused versions from go.sum.
  go.sum
Labels: cla-not-required

#370 Clean up docs using https://get.pinniped.dev redirects.
  deploy/concierge/README.md
  deploy/local-user-authenticator/README.md
  deploy/supervisor/README.md
  site/config.yaml
  site/content/docs/concierge-and-supervisor-demo.md
  site/content/docs/concierge-only-demo.md
  site/themes/pinniped/assets/scss/_syntax.css
  site/themes/pinniped/assets/scss/site.scss
Labels: cla-not-required, documentation, website

#372 Fix get.pinniped.dev latest version redirects.
  site/redirects/get.pinniped.dev/netlify.toml
Labels: bug, cla-not-required, website

#374 Updated the community meeting info with new zoom link and agenda notes
  CONTRIBUTING.md
  README.md
Labels: cla-not-required
